import { Montserrat } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Navbarcomponents/Nav";
import { Providers } from "./Provider";
import Footer from "../components/Footercomponents/Footer";
import FAQ from "@/components/Homecomponets/FAQ";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap"
          rel="stylesheet"
        ></link>
      </head>
      <body className={inter.className}>
        <Providers>
          <Nav />
          {children}
          <FAQ />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
